name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Start backend server
        run: node app.js &
        working-directory: backend

      - name: Run Playwright tests
        run: |
          npm run build
          npm run preview -- --port 5173 &
          npx playwright test
        working-directory: frontend
        env:
          CI: true

      - name: Debug test results
        if: always()
        run: |
          ls -la frontend/playwright-report || echo "No playwright-report directory"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
