name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1' # every Monday at 2 AM UTC

jobs:
  build:
    name: Built
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      CI: true
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            frontend/dist
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

  smoke:
    name: Smoke Tests
    needs: build
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            frontend/dist
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Run smoke tests
        run: npx playwright test --grep="@smoke"
        working-directory: frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: smoke-test-report
          path: frontend/playwright-report/
          retention-days: 7

  regression:
    name: Regression Tests
    needs: smoke
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            frontend/dist
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Run regression tests
        run: npx playwright test --grep="@smoke"
        working-directory: frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: smoke-test-report
          path: frontend/playwright-report/
          retention-days: 7
